server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: buy-service
  data:
    mongodb:
      database: test
      #port: 27017
      #host: localhost
      uri: mongodb+srv://moon:moon@cluster0.fn6vq.mongodb.net/?retryWrites=true&w=majority

#logging
logging:
  file:
    name: e_auction.log
